config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :restaurants
  
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true,
                    length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

def index
  @restaurants = Restaurant.all
end

def new
  @restaurant = Restaurant.new
end

def edit
  @restuarant = Restaurant.find(params[:id])
end

def show
  @restaurant = Restaurant.find(params[:id])
end

def create
  @restaurant = Restaurant.new(restaurant_params)

  if @restaurant.save
    redirect_to @restaurant
  else
    render 'new'
  end
end

def edit
  @restaurant = Restaurant.find(params[:id])
end

def update
  @restaurant = Restaurant.find(params[:id])

  if @restaurant.update(restaurant_params)
    redirect_to @restaurant
  else
    render 'edit'
  end
end

private
  def restaurant_params
    params.require(:restaurant).permit(:name, :description)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hungerhelper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: @restaurant, local: true do |form| %>

<% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@restaurant.errors.count, "error") %>
      prohibited this restaurant from being saved:
    </h2>
    <ul>
      <% @resturant.errors.full_messages do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p><%= form.label :name %></p></br>
<p><%= form.text_field :name %>

<p><%= form.label :description %></p><br>
<p><%= form.text_area :description %>

  <p>
    <%= form.submit %>
  </p>

  <% end %>

app/views/restaurants/edit.html.erb
<h1> Edit restaurant </h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1> List of Restaurants </h1>

<%= link_to 'New Restaurant', new_restaurant_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.description %></td>
      <td><%= link_to 'Show', restaurant_path(restaurant) %></td>
      <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
    </tr>
    <% end %>
  </table>

app/views/restaurants/new.html.erb
<h1> Add a new restaurant!</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
   <strong>Description:</strong>
   <%= @restaurant.description %>
 </p>

 <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
 <%= link_to 'Back', restaurants_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Hunger Helper!</h1>
<p><%= link_to 'List of Restaurants', controller: 'restaurants' %></p>